name: Deploy workflow

on:
    push:
        branches:
            - deploy-workflow

jobs:
    deploy:
        name: Deploy to GitHub Pages
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 16.x
                  cache: npm

            - name: Install dependencies
              run: npm install --frozen-lockfile
            - name: Build website
              env:
                  BASE_URL: /
              run: npm run build

            - name: Push to gh-pages branch
              uses: s0/git-publish-subdir-action@develop
              env:
                  REPO: self
                  BRANCH: gh-pages
                  FOLDER: build
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  MESSAGE: 'Deploy website - based on {sha}'
